data_preprocess:
  target: Revenue
  features:
  - PageValues
  - ExitRates
  - ProductRelated
  - Administrative
  - BounceRates
  - ProductRelated_Duration
  - Administrative_Duration
  - Month
  - Informational_Duration
  categorical_features:
  - Month
train:
  model_type: random_forest
  xgboost:
    random_state: 42
    n_estimators: 75
    learning_rate: 0.05
    objective: binary:logistic
    eval_metric: auc
    max_depth: 3
    subsample: 0.3
    scale_pos_weight: 2.9
  random_forest:
    random_state: 42
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2


